version: '3'

services:
  app:
    image: malulu/php-7.1:latest
    environment:
      - DATABASE_URL=mysql://root:${DB_PW}@servus_db_1:3306/kalli
      - LOCALE=en
    volumes:
      - .:/srv/symfony:rw
    networks:
      - private
      - shared
  web:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    expose:
        - 80
    volumes:
      - ./public:/srv/symfony/public:ro
    environment:
      - VIRTUAL_HOST=kalli-staging.${HOSTNAME}
      - LETSENCRYPT_HOST=kalli-staging.${HOSTNAME}
      - LETSENCRYPT_EMAIL=${EMAIL_ADMIN}
    networks:
      - reverse-proxy
      - private
      - shared
  node:
    image: "node:8"
    user: "root"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
networks:
  reverse-proxy:
    external:
      name: reverseproxy_default
  shared:
    external:
      name: shared
  private:
    driver: bridge